menu:
# - {name: 'courses', url: '/courses'}
- {name: 'About', url: '/'}
- {name: 'Publications', url: '/publications'}
# - {name: 'Video Gallery', url: '/video_gallery'}
# - {name: 'contact', url: '/contact'}

google_analytics: G-9N7779GL13

social:
- {icon: 'github', link: 'https://github.com/chengh-wang'}
- {icon: 'twitter', link: 'https://x.com/330781570'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/chenghao-wang-01a036203/'}
- {icon: 'googleScholar', link: 'https://scholar.google.es/citations?hl=en&user=Vlx-PYwAAAAJ'}